### ISSUE TITLE
no logging returned on docker image

### ISSUE THREAD

**Issue by oc-stephen-bennett** [johnlonganecker/libpostal-rest#13]
Hi, 

im trying to use the docker image but getting no logging output for running parses? docker-compose is set to: 

```
version: '3.8'
services:
  libpostal:
    image: libpostal-rest
    ports:
      - "7050:7050"
    environment:
      - LISTEN_PORT=7050
      - LOG_LEVEL='info'
```

any assistance on what is wrong or missing?
